#!/usr/bin/env python3
"""Generate CATALOG.md from artifact frontmatter — a living index of the commons.

Scans content/ and missions/ for Markdown artifacts, groups them by type, and
writes a grouped catalog with title, status, region/species, and path. Templates
(files under a _templates/ or templates/ directory) are skipped.

Usage: python scripts/build_catalog.py        # writes CATALOG.md
       python scripts/build_catalog.py --check # exit 1 if CATALOG.md is stale
"""
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
SCAN_DIRS = ["content", "missions"]
OUT = ROOT / "CATALOG.md"

# Human-friendly ordering + labels for artifact types.
TYPE_ORDER = [
    ("species-page", "Species Pages"),
    ("region-briefing", "Region Briefings"),
    ("field-mission", "Field Missions"),
    ("observation-guide", "Observation Guides"),
    ("dataset-card", "Dataset Cards"),
    ("research-summary", "Research Summaries"),
    ("partner-profile", "Partner Profiles"),
    ("lesson", "Lessons"),
    ("event-report", "Event Reports"),
    ("funding-proposal", "Funding Proposals"),
    ("notebook", "Notebooks"),
    ("translation", "Translations"),
]


def _frontmatter(text: str):
    if not text.startswith("---"):
        return None
    parts = text.split("---", 2)
    if len(parts) < 3:
        return None
    try:
        return yaml.safe_load(parts[1])
    except yaml.YAMLError:
        return None


def _is_template(path: Path) -> bool:
    return any(part in ("_templates", "templates") for part in path.parts)


def collect() -> dict:
    by_type: dict = {}
    for d in SCAN_DIRS:
        for f in sorted((ROOT / d).rglob("*.md")):
            if _is_template(f):
                continue
            fm = _frontmatter(f.read_text(encoding="utf-8"))
            if not fm or "type" not in fm:
                continue
            by_type.setdefault(fm["type"], []).append((fm, f.relative_to(ROOT)))
    return by_type


def render(by_type: dict) -> str:
    total = sum(len(v) for v in by_type.values())
    lines = [
        "# Blue Life Commons — Catalog",
        "",
        "> Auto-generated by `scripts/build_catalog.py`. Do not edit by hand.",
        "",
        f"**{total} published artifact(s)** across {len([k for k in by_type if by_type[k]])} type(s).",
        "",
    ]
    seen = set()
    for type_key, label in TYPE_ORDER:
        items = by_type.get(type_key)
        if not items:
            continue
        seen.add(type_key)
        lines.append(f"## {label} ({len(items)})")
        lines.append("")
        lines.append("| Title | Status | Scope | Path |")
        lines.append("|---|---|---|---|")
        for fm, path in sorted(items, key=lambda x: str(x[1])):
            scope_bits = []
            if fm.get("species_group"):
                scope_bits.extend(fm["species_group"])
            if fm.get("region"):
                scope_bits.extend(fm["region"])
            scope = ", ".join(str(s) for s in scope_bits) or "—"
            title = str(fm.get("title", "")).replace("|", "\\|")
            lines.append(f"| {title} | {fm.get('status','')} | {scope} | `{path}` |")
        lines.append("")
    # Any types not in TYPE_ORDER
    for type_key in sorted(by_type):
        if type_key in seen:
            continue
        items = by_type[type_key]
        lines.append(f"## {type_key} ({len(items)})")
        lines.append("")
        for fm, path in sorted(items, key=lambda x: str(x[1])):
            lines.append(f"- {fm.get('title','')} — `{path}`")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main(argv) -> int:
    content = render(collect())
    if "--check" in argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != content:
            print("CATALOG.md is stale — run: python scripts/build_catalog.py")
            return 1
        print("CATALOG.md is up to date.")
        return 0
    OUT.write_text(content, encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
